# Generated by Django 3.1.3 on 2021-02-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0039_auto_20210216_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_ptr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filebased_unique_documentpart_related', related_query_name='filebased_unique_documentparts', to='core.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
